name: Install packages & Lint

on: [push]

jobs:
    install-packages:
        name: Install packages & Lint work
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: Install Dependency
              run: npm ci
            
            - name: Cache node_modules
              uses: actions/upload-artifact@v4
              with: 
                name: node
                path: node_modules
            
            # - name: ESlint
            #   run: | 
            #     npm run lint
            #     npm run lint:fix

            # - name: Prettier
            #   run: npm run prettier
    eslint:
        needs: install-packages
        runs-on: ubuntu-latest
        steps:
            - name: Download node_modules
              uses: actions/download-artifact@v4
              with:
                name: node
            
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: ESlint
              run: | 
                npm run lint:fix
                npm run lint

